[package]
name = "common"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
publish = false

[dependencies]
dotenvy = "0.15"
jid = { workspace = true }
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-oslog = "0.1.2"
tracing-subscriber = { workspace = true }