[package]
name = "prose_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = {version = "2.0.4", features = ["full"] }
tracing = { workspace = true }